### ISSUE TITLE
Docker: volume to persist data

### ISSUE THREAD

**Issue by urbany** [mailhog/MailHog#101]
Hi, is there a way to mount a volume to persist the data while using the docker image?
Thanks in advance

**Comment by ian-kent** [comment]
Hi @urbany 

You should be able to do something like this:
```bash
docker run -v `pwd`/docker-maildir:/maildir -p 1025:1025 -p 8025:8025 \
mailhog/mailhog /MailHog -storage maildir -maildir-path=/maildir
```

That should store the messages in a `./docker-maildir` directory, though you can change
```bash
`pwd`/docker-maildir
```
to anything

**Comment by bertoost** [comment]
@ian-kent How to do that in a docker-compose.yml file? Can you provide an example? Something with the command key?

**Comment by rogervila** [comment]
My solution:

´´´
mailhog:
    restart: always
    tty: true
    privileged: true
    container_name: mailhog
    image: mailhog/mailhog:v1.0.0
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./volumes/mailhog/volume:/maildir
    ports:
      - "1025:1025"
      - "8025:8025"
´´´

**Comment by bertoost** [comment]
Thanks @rogervila .. Sorry for my late reply, but it works great!

**Comment by lispercat** [comment]
The proposed solution worked for me only with some modification: I had to start it under root user.
The reason for that is the folder /maildir has the root owner/group and 755 permission.
By default the Mailhog process is started as "mailhog" user so it doesn't have write permission to the /maildir folder

So working config for me would be:
mailhog:
    user: root
    container_name: mailhog
    image: mailhog/mailhog:v1.0.0
    command: ["-storage=maildir", "-maildir-path=/maildir"]
    volumes:
      - ./volumes/mailhog/volume:/maildir
    ports:
      - "1025:1025"
      - "8025:8025"

**Comment by rubanraj54** [comment]
@rogervila solution worked, but I had to set 777 permission to the volumes folder.

`sudo chmod -R 777 ./volumes`

**Comment by xwlee** [comment]
You can also configure using environment values, and set the path to `/home/mailhog` to avoid the permission issue
```yaml
version: '3.8'
services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    volumes:
      - type: volume
        source: mailhog
        target: /home/mailhog
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /home/mailhog
volumes:
  mailhog:

```

**Comment by mannyanebi** [comment]
This worked for me

```
version: "3"

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - 8025:8025
      - 1025:1025
    volumes:
      - mailhog-maildir:/home/mailhog/maildir
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=maildir
    restart: unless-stopped

volumes:
  mailhog-maildir:{}

```
