### ISSUE TITLE
MailHog cannot connect to mongo on Mac

### ISSUE THREAD

**Issue by MaksymSkrynnikov** [mailhog/MailHog#127]
Configuring mailhog in docker-compose file as 
```
 mailhog:
    image: mailhog/mailhog
    depends_on:
      - mongo
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dev-env
    environment:
      MH_STORAGE: mongodb
      MH_MONGO_URI: mongo:27017
```
It works on Linux and stores received messages to MongoDB(mailhog db, messages collection). 
On Mac (El Capitan 10.11.6)  cannot resolve address of container and getting
```
mailhog_1                    | 2016/12/05 10:29:44 Using MongoDB message storage
mailhog_1                    | 2016/12/05 10:29:44 Connecting to MongoDB: mongo:27017
mailhog_1                    | 2016/12/05 10:29:54 Error connecting to MongoDB: no reachable servers
mailhog_1                    | 2016/12/05 10:29:54 MongoDB storage unavailable, reverting to in-memory storage
mailhog_1                    | 2016/12/05 10:29:54 [SMTP] Binding to address: 0.0.0.0:1025
mailhog_1                    | [HTTP] Binding to address: 0.0.0.0:8025
mailhog_1                    | 2016/12/05 10:29:55 Serving under http://0.0.0.0:8025/
mailhog_1                    | Creating API v1 with WebPath:
mailhog_1                    | Creating API v2 with WebPath:
```
