### ISSUE TITLE
SMTP protection

### ISSUE THREAD

**Issue by ogrosko** [mailhog/MailHog#274]
Hello, I have question regarding SMTP server protection.
We run mailhog in docker container on publicly accessible IP. We protect WEB UI with `MH_AUTH_FILE`. Is there a possibility to protect SMTP server with username and password?

docker-compose.yml looks like:
```yml
version: "3.5"

services:
    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        volumes:
            - ./mailhog:/home/mailhog
        environment:
            MH_AUTH_FILE: /home/mailhog/auth.file
        restart: always
        ports:
            - 1025:1025 # smtp server
            - 8025:8025 # web ui
```

Thank you for any hint
