### ISSUE TITLE
How to define a shared maildir for Mailhog in Yaml in a given Storage account?

### ISSUE THREAD

**Issue by Duke4848** [mailhog/MailHog#285]
I have a Mailhog deployed to 2 geographical zones in Azure. I have setup traffic manager for Mailhog, this causes 2 separate in memory mailboxes to exist.

How to define a shared maildir for Mailhog in Yaml in a given Storage account?

**Comment by C-Duv** [comment]
Why in YAML?
Is setting the `MH_MAILDIR_PATH` environment variables or `-maildir-path` command line option incompatible with you setup?
(To use with `MH_STORAGE=maildir` or `-storage=maildir`)

**Comment by Duke4848** [comment]
> Why in YAML?
> Is setting the `MH_MAILDIR_PATH` environment variables or `-maildir-path` command line option incompatible with you setup?
> (To use with `MH_STORAGE=maildir` or `-storage=maildir`)

I did that:

```
 env:
          - name: MH_STORAGE
            value: maildir
          - name: MH_MAILDIR_PATH
            value: path?
```

however I have no idea how pass path to any volume in Azure for instance Storage account of name `xyz`,
