### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by Zacktagnan-ZubiMan** [mailhog/MailHog#292]
Hi:

I am implementing a Laravel project with an email section. I would use your application to test the sending email process.
To get MailHog up, I choose the Docker version so I execute a "docker-compose.yml" file like this on a Windows system:

```
version: '3'

services:

  # MailHog
  ui_web:
    image: mailhog/mailhog
    container_name: cont_mailhog
    tty: true

    ports:
      - '1025:1025'
      - '8025:8025'
    restart: on-failure
```

The Laravel project itself is started through a series of Docker Compose services. So, it's a communication between Docker containers.
Nginx is the web server.

On the ".env" file of my Laravel project, I have this configuration:

```
MAIL_MAILER=smtp
MAIL_HOST=127.0.0.1
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

When I get the order to send the mail, I received this error on the browser:

> **Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to 127.0.0.1:1025 (Connection refused)**

Why the MailHog app doesn't works on my local environment?

Best regards.

**Comment by C-Duv** [comment]
I don't see the part in `docker-compose.yml` where you set environment variables.
You did set them in the `.env` file, but Compose won't pass them to the Docker container automatically: you have to add a `environment` section in the `ui_web` section of your `docker-compose.yml` file.

**Comment by Zacktagnan-ZubiMan** [comment]
Hi:
Are you trying to tell me to include this inside the "docker-compose.yml" to up the service container?:

    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null

Just like this?
On the MailHog documentation, they don't say anything to put these variables when you get the container.

I have to say that I have come to test if it failed, too, by running the entire project environment of Laravel and MySQL without using Docker to start it, and then, everything worked fine regarding sending mails to MailHog and some another email server. And without having to specify anything else in the Docker Compose file, no extra environment variables as you say.

So, seeing that everything worked from my local environment, without using Docker, only, to start MailHog, I had deduced that, perhaps, it could be the part of my Docker Compose environment referred to my work environment with Laravel-MySQL- Nginx, which does not allow sending through a local mail server. And that, perhaps, it requires some added specification to allow it.

I will try what you say despite everything.

See you later.

**Comment by C-Duv** [comment]
The way Docker Compose works is:
Read/Interpret the `docker-compose.ymk` file and execute `docker` (the CLI) commands accordingly.

`docker` CLI has no support of `.env` file, so to set an environment variable to a Docker container you have to use the `-e` option.
Docker Compose does this (id. add in the `-e` option) for you when there is a `environment` section in the service.

About `.env` and Docker Compose now:
Docker Compose will read `.env` file but won't pass it to services because:
* it cannot know which service needs which variable
* variables of `.env` could be for other part than services.
What Docker Compose does with `.env` is:
* read and interpret it (discard comments and load variables names and their value)
* allow variable substitution in the `Docker-compose.yml` file: it will replace `$FOO` by whatever the `FOO` variable is set to in `.env` file.

So you can add the `environnement` part as you did but it won't use the `.env` file :-/

What you can do is:

`.env` file:
```
MAILHOG_MAILER=smtp
MAILHOG_HOST=127.0.0.1
MAILHOG_PORT=1025
MAILHOG_USER=null
MAILHOG_PASSWD=null
MAILHOG_ENCRYPTION=null
```

`docker-compose.yml`:
```YAML
environment:
  MAIL_MAILER: ${MAILHOG_MAILER}
  MAIL_HOST: ${MAILHOG_HOST}
  MAIL_PORT: ${MAILHOG_PORT}
  MAIL_USERNAME: ${MAILHOG_USER}
  MAIL_PASSWORD: ${MAILHOG_PASSWD}
  MAIL_ENCRYPTION: ${MAILHOG_ENCRYPTION}
ports:
    - 1025:${MAILHOG_PORT}
    - 8025:8025
```

**Comment by Zacktagnan-ZubiMan** [comment]
Hi again:

I just try what you tell me. Right now the MailHog Docker Compose file is like this:

```
version: '3'

services:

  # MailHog
  ui_web:
    image: mailhog/mailhog
    container_name: cont_mailhog
    tty: true

    ports:
      - '1025:1025'
      - '8025:8025'
    #restart: always
    restart: on-failure

    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
```
I get up the Laravel-MySQL-Nginx Docker Compose and th MailHog Docker Compose, I access to the website project, I access to the MailHog website also, just like before.
And when I try to send the email to MailHog, I have the same error message like without the environment block you said to put:

> **Connection could not be established with host 127.0.0.1 :stream_socket_client(): unable to connect to 127.0.0.1:1025 (Connection refused)**

I have even defined the same network that is defined in the Laravel-MySQL-Nginx project "docker-compose.yml" file:

```
version: '3'

services:

  # MailHog
  ui_web:
    image: mailhog/mailhog
    container_name: cont_mailhog
    tty: true

    ports:
      - '1025:1025'
      - '8025:8025'
    #restart: always
    restart: on-failure

    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null

    networks:
      - net

networks:
  net:
```

But, it still doesn't work...The same error message.

I've even tried to, instead of starting it separately, include it as another service inside the "docker-compose.yml" of the project and neither

That's the "docker-compose.yml" of the Laravel-MySQL-Nginx project incluiding MailHog like one of the service:

```
version: '3'

services:

  # PHP
  app:
    depends_on:
      - db_server
    build:
      context: ../__docker-img/php
      dockerfile: Dockerfile
    image: laravel-app-img
    container_name: cont_app_${PROY_NAME_ABBREV}
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ../__docker-vol/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - net

  # Nginx
  web_server:
    depends_on:
      - app
    image: nginx:alpine
    tty: true
    ports:
      - '8084:80'
      - '773:443'
    volumes:
      - ./:/var/www/html
      - ../__docker-vol/nginx/conf.d/:/etc/nginx/conf.d/
      - ../__docker-vol/nginx/conf.d/ssl/:/etc/nginx/conf.d/ssl/
    networks:
      - net

  # Composer
  composer_php:
    image: composer
    container_name: cont_composer_${PROY_NAME_ABBREV}
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - net

  # NodeJS
  node_js:
    image: node
    container_name: cont_node_js_${PROY_NAME_ABBREV}
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - net

  # MySQL
  db_server:
    image: mysql:5.7.22
    container_name: cont_db_server_${PROY_NAME_ABBREV}
    tty: true
    ports:
      - '6606:3306'
    env_file: mysql.env
    environment:
      MYSQL_DATABASE: db_${DB_COMMON_DATA}
      MYSQL_USER: usu_${DB_COMMON_DATA}
      MYSQL_PASSWORD: xxxx_${DB_COMMON_DATA}
    volumes:
      - ../__docker-vol/mysql/my.cnf:/etc/mysql/my.cnf
      - ../__docker-vol/mysql/data:/var/lib/mysql/
    networks:
      - net

  # phpMyAdmin
  db_admin:
    depends_on:
      - db_server
    container_name: cont_db_admin_${PROY_NAME_ABBREV}
    image: phpmyadmin/phpmyadmin
    ports:
      - '8094:80'
    env_file: phpmyadmin.env
    volumes:
      - ../__docker-vol/phpmyadmin/conf:/etc/phpmyadmin
    networks:
      - net

  # MailHog
  mailhog_server:
    image: mailhog/mailhog
    container_name: cont_mailhog_server_${PROY_NAME_ABBREV}
    tty: true

    ports:
      - '1025:1025'
      - '8025:8025'
    #restart: always
    restart: on-failure

    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: 127.0.0.1
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null

    networks:
      - net

#Networks
networks:
  net:
```

And always, the same error message when I throw the sending email process.

So, another idea to solve the problem and be able to send emails to MailHog?

Bye.

**Comment by Zacktagnan-ZubiMan** [comment]
Hi:

Finally, I solved the problem with the help of someone else outside this github.

So, to well work the MailHog service implemented within the "docker-compose.yml" file detailed in the previous post and to solve the specified problem, I had to do the following things:

- First, the MailHog service block on the "docker-compose.yml" stays like this:

```
  # MailHog
  #It can be this service name
  ####mailhog:
  #or this one or whatever you want.
  #This name has to be referenced inside the ".env" file
  mailhog_server:
    image: mailhog/mailhog
    container_name: cont_mailhog_server
    #this is optional
    tty: true
    ports:
      - '1025:1025'
      - '8025:8025'
    #this is optional
    #restart: always
    restart: on-failure
    #set the same network as the other services
    networks:
      - net
```

- Then, inside the ".env" file of the Laravel project, it has to refer to the MailHog service name and not to the "127.0.0.1".
For example, if the MailHog service name, inside the "docker-compose.yml" file, is "mailhog_server":

```
MAIL_HOST=mailhog_server
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```

- One more thing, to well apply the changes, there is a option through one Artisan command of the Laravel framework for cleanning the cache:

`php artisan config:cache`

And that's all!! After that, all the email sending process will work fine!!

I hope, that should help someone else.

Bye.
