### ISSUE TITLE
Docker: no persist data

### ISSUE THREAD

**Issue by mferraraUK** [mailhog/MailHog#344]
Hi all, 
I installed on Oracle Linux 8.3 Docker CE Engine 

```
Client: Docker Engine - Community
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:40 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:09 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

After I created a volume with this command:
`docker volume create docker-maildir`

I installed the container MAILHOG and force to use my volume with this command:
`docker run -d -p 25:1025 -p 2080:8025 -v docker-maildir:/maildir --name mailhog --restart unless-stopped mailhog/mailhog`

but if I restart the container I lost the inbox emails.

I tried to access to the container with the command:
`docker exec -it mailhog /bin/sh`

But I don't see any emails in the folders.

**Comment by mferraraUK** [comment]
Hi all, 
I solved with these command:
`docker run -d -p 25:1025 -p 2080:8025 -v mailhog-maildir:/home/mailhog/maildir -v mailhog-smtpconf:/smtp_conf -e MH_STORAGE=maildir -e MH_MAILDIR_PATH=maildir -e MH_OUTGOING_SMTP=/smtp_conf/smtp.json --restart unless-stopped --name mailhog mailhog/mailhog`

But I have to set the permission for the volume as 777 otherwise from mailhog I can’t write emails to the volume mounted.

**Comment by lauer** [comment]
I had no problems if the mailhog homedir is mounted. 
Example for docker-compose

```
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=maildir
    volumes:
      - mailhog:/home/mailhog
```
