### ISSUE TITLE
Cannot change MH_SMTP_BIND_ADDR

### ISSUE THREAD

**Issue by OxyTJ** [mailhog/MailHog#377]
Hello,

I've set up a MailHog container using docker compose using the following configuration:

```
version: "3.8"
services:
  mailhog:
    image: mailhog/mailhog:latest
    container_name: MailHog
    environment:
      - TZ='America/Chicago
    ports:
      - 1025:1025/tcp
      - 8025:8025/tcp
    volumes:
      - type: bind
        source: /data/mailhog
        target: /data/mailhog
    restart: unless-stopped
```

I noticed when running `docker-compose up`, it states that the SMTP address is bound to address `0.0.0.0:1025`. I need to bind it to the hostname of the VM that MailHog is running on so that I can connect to it from apps running on separate VMs. However, whenever I set the `MH_SMTP_BIND_ADDR` environment variable, per https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md, and run `docker-compose up`, the container fails stating port 1025/tcp is an unknown port. Any idea why this is?
