### ISSUE TITLE
Passing outgoing smtp file with docker-compose

### ISSUE THREAD

**Issue by SamTyurenkov** [mailhog/MailHog#452]
H, 

Is there a way to pass outgoing smtp json without custom docker image? 

```
version: '3'

services:
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 1025:1025  # SMTP port for sending emails
      - 8025:8025  # Web UI for viewing emails
    volumes:
      - ./mailhog.cfg.json:/mailhog.cfg.json
    command: ["-outgoing-smtp", "/mailhog.cfg.json"]
```

If i try it this way, - a directory is created instead of copying a file. 
is there a way to pass .json to Mailhog in Docker without creating custom Docker Image?
