### ISSUE TITLE
Can't connect to localhost:1025

### ISSUE THREAD

**Issue by vialcollet** [mailhog/MailHog#60]
Hi.
I have tried to use MailHog which seems promising.
However, after running the binary (on Windows 7), I can access the Web UI but my php application returns that it can't connect to localhost:1025 (timed out).
I am using swiftmailer with the following config:

```
swiftmailer:
    transport:      smtp
    username:       testuser
    password:       testpwd
    host:           127.0.0.1
    port:           1025
    encryption:     null
    auth_mode:      plain
```

Am i missing something?

Thanks in advance

**Comment by ian-kent** [comment]
Hi @vialcollet 

Are any errors output when you start MailHog? If it can't bind to the specified port it should output something similar to these:
```
[SMTP] Error binding to address :25: listen tcp :25: bind: permission denied
[SMTP] Error binding to address :1025: listen tcp :1025: bind: address already in use
```

I'll try to reproduce the problem on Windows 7 when I get a chance, but it should just work :smile:

**Comment by nthum** [comment]
Same here. It hangs connecting to localhost:1025 but Web UI seems to be fine

**Comment by jcornide** [comment]
I have the same problem, I can connect to the ui (but from outside the host) but I can't use mailhog from the same host

**Comment by n3o77** [comment]
I'm using the following setting with swiftmailer and it works:

```yml
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode: "%mailer_auth_mode%"
    port:      "%mailer_port%"
    spool:     { type: memory }
```

```yml
parameters:
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    mailer_auth_mode: null
    mailer_port: 1025
```
